export const FETCH_STRATEGIC_CARDS_REQ = 'FETCH_STRATEGIC_CARDS_REQ';
export const FETCH_STRATEGIC_CARDS_SUCCESS = 'FETCH_STRATEGIC_CARDS_SUCCESS';
export const FETCH_STRATEGIC_CARDS_FAILURE = 'FETCH_STRATEGIC_CARDS_FAILURE';


//for footer

export const FOOTER_FETCH_REQ = "FOOTER_FETCH_REQ";
export const FOOTER_FETCH_SUCCESS = "FOOTER_FETCH_SUCCESS";
export const FOOTER_FETCH_FAILURE = "FOOTER_FETCH_FAILURE";

// feature items


// export const FEATURE_FETCH_REQ = "FEATURE_FETCH_REQ";
// export const FEATURE_FETCH_SUCCESS = "FEATURE_FETCH_SUCCESS";
// export const FEATURE_FETCH_FAILURE  = "FEATURE_FETCH_FAILURE";


export const PLACE_HOLDER = 'PLACE_HOLDER';